// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Persistence.Context;

#nullable disable

namespace Portfolio.Persistence.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    partial class PortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ContactMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Storage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Files");

                    b.HasDiscriminator<string>("Discriminator").HasValue("File");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Identity.AspRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Identity.AspUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.PersonalInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Github")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instagram")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medium")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telegram")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PersonalInfo");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CoverImageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CoverImageId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Testimonial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Timeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Timelines");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProjectImageFile", b =>
                {
                    b.HasBaseType("Portfolio.Domain.Entities.File");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasIndex("ProjectId");

                    b.HasDiscriminator().HasValue("ProjectImageFile");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ResumeFile", b =>
                {
                    b.HasBaseType("Portfolio.Domain.Entities.File");

                    b.Property<int?>("resumeLanguage")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("ResumeFile");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.SiteImageFile", b =>
                {
                    b.HasBaseType("Portfolio.Domain.Entities.File");

                    b.Property<int>("SiteImageType")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("SiteImageFile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Identity.AspRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Identity.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Identity.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Identity.AspRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Domain.Entities.Identity.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Identity.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Category", b =>
                {
                    b.OwnsOne("Portfolio.Domain.ValueObjects.MultiLanguageString", "Name", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("De")
                                .HasColumnType("TEXT");

                            b1.Property<string>("En")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Language", b =>
                {
                    b.OwnsOne("Portfolio.Domain.ValueObjects.MultiLanguageString", "Name", b1 =>
                        {
                            b1.Property<Guid>("LanguageId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("De")
                                .HasColumnType("TEXT");

                            b1.Property<string>("En")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.PersonalInfo", b =>
                {
                    b.OwnsOne("Portfolio.Domain.ValueObjects.MultiLanguageString", "Biography", b1 =>
                        {
                            b1.Property<Guid>("PersonalInfoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("De")
                                .HasColumnType("TEXT");

                            b1.Property<string>("En")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PersonalInfoId");

                            b1.ToTable("PersonalInfo");

                            b1.WithOwner()
                                .HasForeignKey("PersonalInfoId");
                        });

                    b.OwnsOne("Portfolio.Domain.ValueObjects.MultiLanguageString", "Title", b1 =>
                        {
                            b1.Property<Guid>("PersonalInfoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("De")
                                .HasColumnType("TEXT");

                            b1.Property<string>("En")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PersonalInfoId");

                            b1.ToTable("PersonalInfo");

                            b1.WithOwner()
                                .HasForeignKey("PersonalInfoId");
                        });

                    b.Navigation("Biography")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Project", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Category", "Category")
                        .WithMany("Projects")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Domain.Entities.ProjectImageFile", "CoverImage")
                        .WithMany()
                        .HasForeignKey("CoverImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Portfolio.Domain.ValueObjects.MultiLanguageString", "Description", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("De")
                                .HasColumnType("TEXT");

                            b1.Property<string>("En")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("Portfolio.Domain.ValueObjects.MultiLanguageString", "Title", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("De")
                                .HasColumnType("TEXT");

                            b1.Property<string>("En")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Category");

                    b.Navigation("CoverImage");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Skill", b =>
                {
                    b.OwnsOne("Portfolio.Domain.ValueObjects.MultiLanguageString", "Title", b1 =>
                        {
                            b1.Property<Guid>("SkillId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("De")
                                .HasColumnType("TEXT");

                            b1.Property<string>("En")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("SkillId");

                            b1.ToTable("Skills");

                            b1.WithOwner()
                                .HasForeignKey("SkillId");
                        });

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Testimonial", b =>
                {
                    b.OwnsOne("Portfolio.Domain.ValueObjects.MultiLanguageString", "Comment", b1 =>
                        {
                            b1.Property<Guid>("TestimonialId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("De")
                                .HasColumnType("TEXT");

                            b1.Property<string>("En")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("TestimonialId");

                            b1.ToTable("Testimonials");

                            b1.WithOwner()
                                .HasForeignKey("TestimonialId");
                        });

                    b.Navigation("Comment")
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Timeline", b =>
                {
                    b.OwnsOne("Portfolio.Domain.ValueObjects.MultiLanguageString", "CompanyOrSchool", b1 =>
                        {
                            b1.Property<Guid>("TimelineId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("De")
                                .HasColumnType("TEXT");

                            b1.Property<string>("En")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("TimelineId");

                            b1.ToTable("Timelines");

                            b1.WithOwner()
                                .HasForeignKey("TimelineId");
                        });

                    b.OwnsOne("Portfolio.Domain.ValueObjects.MultiLanguageString", "Description", b1 =>
                        {
                            b1.Property<Guid>("TimelineId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("De")
                                .HasColumnType("TEXT");

                            b1.Property<string>("En")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("TimelineId");

                            b1.ToTable("Timelines");

                            b1.WithOwner()
                                .HasForeignKey("TimelineId");
                        });

                    b.OwnsOne("Portfolio.Domain.ValueObjects.MultiLanguageString", "Title", b1 =>
                        {
                            b1.Property<Guid>("TimelineId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("De")
                                .HasColumnType("TEXT");

                            b1.Property<string>("En")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("TimelineId");

                            b1.ToTable("Timelines");

                            b1.WithOwner()
                                .HasForeignKey("TimelineId");
                        });

                    b.Navigation("CompanyOrSchool")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProjectImageFile", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Category", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Project", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
