import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';

export type LanguageCode = 'tr' | 'en' | 'de';

@Injectable({
  providedIn: 'root'
})
export class LocalizationService {
  private readonly defaultLang: LanguageCode = 'tr';
  private readonly langKey = 'app_language';

  private currentLangSubject: BehaviorSubject<LanguageCode>;
  public currentLang$: Observable<LanguageCode>;

  private readonly translations: Record<LanguageCode, Record<string, string>> = {
    tr: {
      "NAV_HOME": "ANASAYFA",
      "NAV_ABOUT": "HAKKIMDA",
      "NAV_PORTFOLIO": "PORTFOLYO",
      "NAV_BLOG": "BLOG",
      "NAV_CONTACT": "İLETİŞİM",
      "HERO_SUBTITLE": "YAZILIM MİMARİSİ & MÜHENDİSLİK",
      "HERO_TITLE": "Designing & Constructing Scalable Web Environments",
      "CORE_STACK": "Teknoloji Havuzu",
      "OPERATIONAL_MATRIX": "Çalışma Matrisi",
      "ENGINEERING_ACTIVITIES": "Mühendislik Günlüğü",
      "HIRE_ME": "İletişime Geç",
      "SEARCH_PLACEHOLDER": "Proje veya makale ara...",
      "CV_DOWNLOAD": "Özgeçmiş (CV) İndir",
      "READ_ARTICLE": "Makaleyi Oku",
      "VIEW_DETAILS": "Detayları İncele",
      "BACK_TO_HOME": "Anasayfaya Dön",
      "PROJECT_INFO": "Proje Bilgileri",
      "CLIENT": "Müşteri",
      "DATE": "Tarih",
      "TECH_STACK": "Kullanılan Teknolojiler",
      "SOURCE_CODE": "Kaynak Kodu",
      "DEMO": "Canlı Demo",
      "CONTACT_TITLE": "İletişime Geçin",
      "CONTACT_SUB": "Projeleriniz veya işbirlikleri için mesaj gönderebilirsiniz.",
      "YOUR_NAME": "Adınız",
      "YOUR_EMAIL": "E-posta Adresiniz",
      "MESSAGE": "Mesajınız",
      "SEND_MESSAGE": "Mesajı Gönder",
      "OR_DIRECT": "VEYA DOĞRUDAN CV İNDİRİN",
      "CLOSE": "Kapat",
      "DAYS_LOG": "Günlük Log",
      "REPOSITORIES": "Proje",
      "PUBLICATIONS": "Yayın",
      "ABOUT_SUBTITLE": "KİŞİSEL BİYOGRAFİ",
      "ABOUT_TITLE": "Hakkımda",
      "ABOUT_INTRO_1_PREFIX": "Merhabalar, ben ",
      "ABOUT_INTRO_1_SUFFIX": "Bilişim sektöründe 10 yılı aşkın süredir kıdemli yazılım mühendisi ve sistem mimarı olarak görev almaktayım. Kariyerim boyunca yüksek ölçekli dağıtık arka uç servisleri, gerçek zamanlı veri akış mimarileri ve ilişkisel/ilişkisel olmayan veri tabanlarının ölçeklenmesi ve optimizasyonu üzerine odaklandım.",
      "ABOUT_INTRO_2": "Clean Code prensiplerine bağlı kalarak sürdürülebilir, modüler kod yazımı ve modern entegrasyon süreçlerinin (CI/CD) otomasyonu konularında ekiplere rehberlik etmekteyim. Teknolojik zorlukları çözmeyi, performansı en üst seviyeye taşımayı ve açık kaynak kodlu projeler ile topluluğa katkı sağlamayı amaç ediniyorum.",
      "ABOUT_INTERESTS": "Hizmetler",
      "SERVICES_SUBTITLE": "UZMANLIK & HİZMETLER",
      "INTEREST_1_TITLE": "Sistem Mimarisi",
      "INTEREST_1_DESC": "Dağınık sistemler, gerçek zamanlı veri akışı ve SignalR hub altyapıları.",
      "INTEREST_2_TITLE": "Performans Optimizasyonu",
      "INTEREST_2_DESC": "Veri tabanı indeksleme, SQL sorgu iyileştirme ve arka uç cache yapılandırmaları.",
      "INTEREST_3_TITLE": "Bulut Teknolojileri",
      "INTEREST_3_DESC": "AWS bulut mimarileri, CI/CD hatları ve Docker konteynerizasyon süreçleri.",
      "CV_TITLE": "Özgeçmiş",
      "CV_SUBTITLE": "PROFESYONEL GEÇMİŞ",
      "CV_LOCATION": "İstanbul, Türkiye",
      "CV_DOWNLOAD_FOOTER": "Güncel özgeçmişimi tercih ettiğiniz dilde PDF formatında indirebilirsiniz:",
      "CV_SUMMARY": "Kariyer yolculuğum, üstlendiğim roller ve teknik yetkinliklerime ait detaylı özgeçmişime aşağıdan ulaşabilirsiniz.",
      "HEATMAP_IDLE": "Sakin",
      "HEATMAP_PEAK": "Yoğun",
      "ACT_TAG_PUB": "Yayın / Makale",
      "ACT_TAG_RELEASE": "Paket Yayını",
      "ACT_TAG_INFRA": "Altyapı Güncellemesi",
      "ACT_TIME_3D": "3 gün önce",
      "ACT_TIME_1W": "1 hafta önce",
      "ACT_TIME_2W": "2 hafta önce",
      "ACT_TIME_3W": "3 hafta önce",
      "ACT_1_TITLE": ".NET Core SignalR ve Gerçek Zamanlı İstemciler Derinlemesine Bakış",
      "ACT_1_DESC": "Soket el sıkışmaları, istemci bağlantısının güvenli şekilde kesilmesi ve Hub'lar kullanılarak telemetri akışlarının senkronize edilmesi için temel mimarilerin analizi.",
      "ACT_2_TITLE": "Platar LPR — Plaka Tanıma Web Paneli",
      "ACT_2_DESC": "Canlı otomatik plaka okuyucu girdilerini görselleştirmek, eşleştirmek ve kataloglamak için saf JS ile yazılmış hafif bir gösterge paneli modülü yayınlandı.",
      "ACT_3_TITLE": "Estetik Web Tasarımı: CSS ile Glassmorphic Efektler Oluşturma",
      "ACT_3_DESC": "Cam panel konteynerleri için backdrop-filter özellikleri, özel iç kenarlık gölgesi parametreleri ve CSS maske ayarlarını detaylandıran modüler bir rehber.",
      "ACT_4_TITLE": "Telemetri loglarındaki veri tabanı sorgu indeksleri optimize edildi",
      "ACT_4_DESC": "Büyük log tablolarında sorgu gecikme sürelerini %35 oranında kısaltan yapısal indeks değişiklikleri birleştirildi.",
      "PORTFOLIO_SUBTITLE": "PROJELER & UYGULAMALAR",
      "PORTFOLIO_TITLE": "Projelerim",
      "PORTFOLIO_DESC": "Geliştirdiğim açık kaynak kodlu modüller, ticari platformlar ve yapay zeka entegrasyonları.",
      "FILTER_ALL": "Tümü",
      "FILTER_OTHER": "Diğer",
      "SEARCH_PROJ_PLACEHOLDER": "Proje veya teknoloji ara...",
      "SEARCH_BLOG_PLACEHOLDER": "Makale başlığı veya etiket ara...",
      "NO_PROJECTS_FOUND": "Arama kriterlerinize uygun proje bulunamadı.",
      "NO_ARTICLES_FOUND": "Arama kriterlerinize uygun makale bulunamadı.",
      "SEARCH_RESULT": "Arama Sonucu",
      "BLOG_SUBTITLE": "BİLGİ PAYLAŞIMI & MAKALELER",
      "BLOG_TITLE": "Blog Yazılarım",
      "CAT_ARCHITECTURE": "Yazılım Mimarisi",
      "CAT_AI": "Yapay Zeka",
      "CAT_FRONTEND": "Ön Uç & Tasarım",
      "CAT_OTHER": "Diğer",
      "PROJECT_DETAILS_TITLE": "PROJE DETAYLI BİLGİLERİ",
      "PROJECT_METADATA": "Masaüstü Verileri",
      "CATEGORY": "Kategori",
      "PROJECT_LINK": "Proje Linki",
      "VIEW_CODE_GITHUB": "KODLARI GÖRÜNTÜLE (GITHUB)",
      "PREV_IMAGE": "Önceki Görsel",
      "NEXT_IMAGE": "Sonraki Görsel",
      "IMAGE_ALT": "Görseli",
      "BACK_TO_BLOG": "Blog Listesine Dön",
      "MIN_READ": "dk okuma",
      "LOCATION_VAL": "Kayseri, Türkiye",
      "OPEN_TO_OFFERS": "Yeni Tekliflere Açık",
      "CLOSED_TO_OFFERS": "Tekliflere Kapalı"
    },
    en: {
      "NAV_HOME": "HOME",
      "NAV_ABOUT": "ABOUT ME",
      "NAV_PORTFOLIO": "PORTFOLIO",
      "NAV_BLOG": "BLOG",
      "NAV_CONTACT": "CONTACT",
      "HERO_SUBTITLE": "SOFTWARE ARCHITECTURE & ENGINEERING",
      "HERO_TITLE": "Designing & Constructing Scalable Web Environments",
      "CORE_STACK": "Core Engineering Stack",
      "OPERATIONAL_MATRIX": "Operational Matrix",
      "ENGINEERING_ACTIVITIES": "Engineering Activities",
      "HIRE_ME": "Get in Touch",
      "SEARCH_PLACEHOLDER": "Search projects or articles...",
      "CV_DOWNLOAD": "Download Resume (CV)",
      "READ_ARTICLE": "Read Article",
      "VIEW_DETAILS": "View Details",
      "BACK_TO_HOME": "Back to Home",
      "PROJECT_INFO": "Project Info",
      "CLIENT": "Client",
      "DATE": "Date",
      "TECH_STACK": "Tech Stack",
      "SOURCE_CODE": "Source Code",
      "DEMO": "Live Demo",
      "CONTACT_TITLE": "Get in Touch",
      "CONTACT_SUB": "Let's discuss how we can work together or collaborate on your next project.",
      "YOUR_NAME": "Your Name",
      "YOUR_EMAIL": "Your Email",
      "MESSAGE": "Message",
      "SEND_MESSAGE": "Send Message",
      "OR_DIRECT": "OR DOWNLOAD DIRECT CV",
      "CLOSE": "Close",
      "DAYS_LOG": "Days Log",
      "REPOSITORIES": "Projects",
      "PUBLICATIONS": "Publications",
      "ABOUT_SUBTITLE": "PERSONAL BIOGRAPHY",
      "ABOUT_TITLE": "About Me",
      "ABOUT_INTRO_1_PREFIX": "Hello, I am ",
      "ABOUT_INTRO_1_SUFFIX": "I have been working in the IT sector for over 10 years as a senior software engineer and system architect. Throughout my career, I have focused on large-scale distributed backend services, real-time data streaming architectures, and the scaling and optimization of relational/non-relational databases.",
      "ABOUT_INTRO_2": "Adhering to Clean Code principles, I guide teams in writing sustainable, modular code and automating modern integration processes (CI/CD). I aim to solve technological challenges, maximize performance, and contribute to the community with open-source projects.",
      "ABOUT_INTERESTS": "Services",
      "SERVICES_SUBTITLE": "EXPERTISE & SERVICES",
      "INTEREST_1_TITLE": "System Architecture",
      "INTEREST_1_DESC": "Distributed systems, real-time data flows, and SignalR hub infrastructures.",
      "INTEREST_2_TITLE": "Performance Optimization",
      "INTEREST_2_DESC": "Database indexing, SQL query optimization, and backend caching setups.",
      "INTEREST_3_TITLE": "Cloud Technologies",
      "INTEREST_3_DESC": "AWS cloud architectures, CI/CD pipelines, and Docker containerization processes.",
      "CV_TITLE": "Resume",
      "CV_SUBTITLE": "PROFESSIONAL PROFILE",
      "CV_LOCATION": "Istanbul, Turkey",
      "CV_DOWNLOAD_FOOTER": "You can download my current resume in your preferred language in PDF format:",
      "CV_SUMMARY": "You can access my detailed resume below, highlighting my career journey, roles, and technical expertise.",
      "HEATMAP_IDLE": "Idle",
      "HEATMAP_PEAK": "Peak",
      "ACT_TAG_PUB": "Technical Publication",
      "ACT_TAG_RELEASE": "Package Release",
      "ACT_TAG_INFRA": "Infrastructure Update",
      "ACT_TIME_3D": "3 days ago",
      "ACT_TIME_1W": "1 week ago",
      "ACT_TIME_2W": "2 weeks ago",
      "ACT_TIME_3W": "3 weeks ago",
      "ACT_1_TITLE": "Deep Dive into .NET Core SignalR and Real-time Clients",
      "ACT_1_DESC": "Analyzing core architectures for handling socket handshakes, client disconnections gracefully, and syncing telemetry streams using Hubs.",
      "ACT_2_TITLE": "Platar LPR — License Plate Recognition Web Dashboard",
      "ACT_2_DESC": "Released a lightweight dashboard module in pure JS for visualizing, mapping, and cataloging live automatic number-plate reader inputs.",
      "ACT_3_TITLE": "Aesthetic Web Design: Crafting Glassmorphism Effects using CSS",
      "ACT_3_DESC": "A modular tutorial detailing backdrop-filters, custom inner border shadow parameters, and CSS mask settings for glass dashboard containers.",
      "ACT_4_TITLE": "Optimized database query indexes on telemetry logs",
      "ACT_4_DESC": "Merged structural index alterations which shortened query latency times by 35% across massive logs tables.",
      "PORTFOLIO_SUBTITLE": "PROJECTS & APPLICATIONS",
      "PORTFOLIO_TITLE": "My Projects",
      "PORTFOLIO_DESC": "Open source modules, commercial platforms, and AI integrations that I developed.",
      "FILTER_ALL": "All",
      "FILTER_OTHER": "Other",
      "SEARCH_PROJ_PLACEHOLDER": "Search project or tech...",
      "SEARCH_BLOG_PLACEHOLDER": "Search article title or tag...",
      "NO_PROJECTS_FOUND": "No projects found matching your search criteria.",
      "NO_ARTICLES_FOUND": "No articles found matching your search criteria.",
      "SEARCH_RESULT": "Search Result",
      "BLOG_SUBTITLE": "KNOWLEDGE SHARING & ARTICLES",
      "BLOG_TITLE": "My Blog Posts",
      "CAT_ARCHITECTURE": "Software Architecture",
      "CAT_AI": "Artificial Intelligence",
      "CAT_FRONTEND": "Frontend & Design",
      "CAT_OTHER": "Other",
      "PROJECT_DETAILS_TITLE": "PROJECT DETAILED INFORMATION",
      "PROJECT_METADATA": "Project Specifications",
      "CATEGORY": "Category",
      "PROJECT_LINK": "Project Link",
      "VIEW_CODE_GITHUB": "VIEW SOURCE CODE (GITHUB)",
      "PREV_IMAGE": "Previous Image",
      "NEXT_IMAGE": "Next Image",
      "IMAGE_ALT": "Image",
      "BACK_TO_BLOG": "Back to Blog List",
      "MIN_READ": "min read",
      "LOCATION_VAL": "Kayseri, Turkey",
      "OPEN_TO_OFFERS": "Open to Opportunities",
      "CLOSED_TO_OFFERS": "Not Seeking Opportunities"
    },
    de: {
      "NAV_HOME": "STARTSEITE",
      "NAV_ABOUT": "ÜBER MICH",
      "NAV_PORTFOLIO": "PORTFOLIO",
      "NAV_BLOG": "BLOG",
      "NAV_CONTACT": "KONTAKT",
      "HERO_SUBTITLE": "SOFTWAREARCHITEKTUR & ENGINEERING",
      "HERO_TITLE": "Konzeption & Entwicklung skalierbarer Webumgebungen",
      "CORE_STACK": "Technologie-Stack",
      "OPERATIONAL_MATRIX": "Aktivitätsmatrix",
      "ENGINEERING_ACTIVITIES": "Engineering-Aktivitäten",
      "HIRE_ME": "Kontaktieren",
      "SEARCH_PLACEHOLDER": "Projekte oder Artikel suchen...",
      "CV_DOWNLOAD": "Lebenslauf (CV) herunterladen",
      "READ_ARTICLE": "Artikel lesen",
      "VIEW_DETAILS": "Details anzeigen",
      "BACK_TO_HOME": "Zurück zur Startseite",
      "PROJECT_INFO": "Projektinfo",
      "CLIENT": "Kunde",
      "DATE": "Datum",
      "TECH_STACK": "Verwendete Technologien",
      "SOURCE_CODE": "Quellcode",
      "DEMO": "Live-Demo",
      "CONTACT_TITLE": "Kontakt aufnehmen",
      "CONTACT_SUB": "Lassen Sie uns besprechen, wie wir zusammenarbeiten können.",
      "YOUR_NAME": "Ihr Name",
      "YOUR_EMAIL": "Ihre E-Mail",
      "MESSAGE": "Nachricht",
      "SEND_MESSAGE": "Nachricht senden",
      "OR_DIRECT": "ODER CV DIREKT HERUNTERLADEN",
      "CLOSE": "Schließen",
      "DAYS_LOG": "Tage Log",
      "REPOSITORIES": "Projekte",
      "PUBLICATIONS": "Veröffentlichungen",
      "ABOUT_SUBTITLE": "PERSÖNLICHE BIOGRAFIE",
      "ABOUT_TITLE": "Über mich",
      "ABOUT_INTRO_1_PREFIX": "Hallo, ich bin ",
      "ABOUT_INTRO_1_SUFFIX": "Ich bin seit über 10 Jahren in der IT-Branche als Senior Software Engineer und Systemarchitekt tätig. Im Laufe meiner Karriere habe ich mich auf hochskalierbare verteilte Backend-Dienste, Echtzeit-Daten-Streaming-Architekturen sowie die Skalierung und Optimierung von relationalen/nicht-relationalen Datenbanken konzentriert.",
      "ABOUT_INTRO_2": "Unter Einhaltung von Clean-Code-Prinzipien leite ich Teams beim Schreiben von nachhaltigem, modularem Code und der Automatisierung moderner Integrationsprozesse (CI/CD) an. Mein Ziel ist es, technologische Herausforderungen zu lösen, die Performance zu maximieren und mit Open-Source-Projekten zur Community beizutragen.",
      "ABOUT_INTERESTS": "Dienstleistungen",
      "SERVICES_SUBTITLE": "EXPERTISE & LEISTUNGEN",
      "INTEREST_1_TITLE": "Systemarchitektur",
      "INTEREST_1_DESC": "Verteilte Systeme, Echtzeit-Datenströme und SignalR-Hub-Infrastrukturen.",
      "INTEREST_2_TITLE": "Performance-Optimierung",
      "INTEREST_2_DESC": "Datenbank-Indizierung, SQL-Abfrageoptimierung und Backend-Caching-Konfigurationen.",
      "INTEREST_3_TITLE": "Wolken-Technologien",
      "INTEREST_3_DESC": "AWS-Cloud-Architekturen, CI/CD-Pipelines und Docker-Containerisierungsprozesse.",
      "CV_TITLE": "Lebenslauf",
      "CV_SUBTITLE": "BERUFLICHER WERDEGANG",
      "CV_LOCATION": "Istanbul, Türkei",
      "CV_DOWNLOAD_FOOTER": "Sie können meinen aktuellen Lebenslauf in Ihrer bevorzugten Sprache als PDF herunterladen:",
      "CV_SUMMARY": "Meinen detaillierten Lebenslauf mit Informationen zu meinem Werdegang, meinen Rollen und technischen Kompetenzen finden Sie unten.",
      "HEATMAP_IDLE": "Inaktiv",
      "HEATMAP_PEAK": "Spitze",
      "ACT_TAG_PUB": "Veröffentlichung",
      "ACT_TAG_RELEASE": "Paket-Release",
      "ACT_TAG_INFRA": "Infrastruktur-Update",
      "ACT_TIME_3D": "Vor 3 Tagen",
      "ACT_TIME_1W": "Vor 1 Woche",
      "ACT_TIME_2W": "Vor 2 Wochen",
      "ACT_TIME_3W": "Vor 3 Wochen",
      "ACT_1_TITLE": "Tiefer Einblick in .NET Core SignalR und Echtzeit-Clients",
      "ACT_1_DESC": "Analyse von Kernarchitekturen für Socket-Handshakes, Client-Disconnections und Synchronisierung von Telemetriedaten mit Hubs.",
      "ACT_2_TITLE": "Platar LPR — Kennzeichenerkennung Web-Dashboard",
      "ACT_2_DESC": "Veröffentlichung eines leichtgewichtigen Dashboard-Moduls in reinem JS zur Visualisierung und Katalogisierung von LPR-Daten.",
      "ACT_3_TITLE": "Ästhetisches Webdesign: Glassmorphismus-Effekte mit CSS",
      "ACT_3_DESC": "Ein modulares Tutorial über Backdrop-Filter, innere Randschatten und CSS-Masken für Cam-Panel-Container.",
      "ACT_4_TITLE": "Optimierte Datenbankabfrageindizes für Telemetrieprotokolle",
      "ACT_4_DESC": "Zusammenführung struktureller Indexänderungen, die Abfragezeiten bei großen Protokolltabellen um 35% verkürzten.",
      "PORTFOLIO_SUBTITLE": "PROJEKTE & ANWENDUNGEN",
      "PORTFOLIO_TITLE": "Meine Projekte",
      "PORTFOLIO_DESC": "Open-Source-Module, kommerzielle Plattformen und KI-Integrationen, die ich entwickelt habe.",
      "FILTER_ALL": "Alle",
      "FILTER_OTHER": "Andere",
      "SEARCH_PROJ_PLACEHOLDER": "Projekt oder Tech suchen...",
      "SEARCH_BLOG_PLACEHOLDER": "Artikel oder Tag suchen...",
      "NO_PROJECTS_FOUND": "Keine Projekte gefunden, die Ihren Suchkriterien entsprechen.",
      "NO_ARTICLES_FOUND": "Keine Artikel gefunden, die Ihren Suchkriterien entsprechen.",
      "SEARCH_RESULT": "Suchergebnis",
      "BLOG_SUBTITLE": "WISSENSTRANSFER & ARTIKEL",
      "BLOG_TITLE": "Meine Blogbeiträge",
      "CAT_ARCHITECTURE": "Softwarearchitektur",
      "CAT_AI": "Künstliche Intelligenz",
      "CAT_FRONTEND": "Frontend & Design",
      "CAT_OTHER": "Andere",
      "PROJECT_DETAILS_TITLE": "PROJEKT-DETAILINFORMATIONEN",
      "PROJECT_METADATA": "Projektdaten",
      "CATEGORY": "Kategorie",
      "PROJECT_LINK": "Projekt-Link",
      "VIEW_CODE_GITHUB": "QUELLCODE ANZEIGEN (GITHUB)",
      "PREV_IMAGE": "Vorheriges Bild",
      "NEXT_IMAGE": "Nächstes Bild",
      "IMAGE_ALT": "Bild",
      "BACK_TO_BLOG": "Zurück zur Blog-Liste",
      "MIN_READ": "Min. Lesezeit",
      "LOCATION_VAL": "Kayseri, Türkei",
      "OPEN_TO_OFFERS": "Offen für Angebote",
      "CLOSED_TO_OFFERS": "Keine Angebote gesucht"
    }
  };

  constructor() {
    let savedLang = this.defaultLang;
    if (typeof window !== 'undefined' && window.localStorage) {
      const saved = localStorage.getItem(this.langKey) as LanguageCode;
      if (saved === 'tr' || saved === 'en' || saved === 'de') {
        savedLang = saved;
      }
    }
    this.currentLangSubject = new BehaviorSubject<LanguageCode>(savedLang);
    this.currentLang$ = this.currentLangSubject.asObservable();
  }

  public getLanguage(): LanguageCode {
    return this.currentLangSubject.value;
  }

  public setLanguage(lang: LanguageCode): void {
    if (typeof window !== 'undefined' && window.localStorage) {
      localStorage.setItem(this.langKey, lang);
    }
    this.currentLangSubject.next(lang);
  }

  public translate(key: string): string {
    const lang = this.getLanguage();
    return this.translations[lang]?.[key] || key;
  }
}
