using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Server.Data;
using Server.Models;

namespace Server.Services
{
    public interface IDatabaseSeeder
    {
        void Seed();
    }

    public class DatabaseSeeder : IDatabaseSeeder
    {
        private readonly AppDbContext _db;

        public DatabaseSeeder(AppDbContext db)
        {
            _db = db;
        }

        public void Seed()
        {
            if (_db.Database.ProviderName == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                try
                {
                    _db.Database.ExecuteSqlRaw(@"
                        CREATE TABLE IF NOT EXISTS ""__EFMigrationsHistory"" (
                            ""MigrationId"" character varying(150) NOT NULL,
                            ""ProductVersion"" character varying(32) NOT NULL,
                            CONSTRAINT ""PK___EFMigrationsHistory"" PRIMARY KEY (""MigrationId"")
                        );
                        
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""CvText_TR"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""CvText_EN"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""CvText_DE"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""CvPdfUrl_TR"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""CvPdfUrl_EN"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""CvPdfUrl_DE"" text;
                        
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""Job_TR"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""Job_EN"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""Job_DE"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""Education_TR"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""Education_EN"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""Education_DE"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""Motto_TR"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""Motto_EN"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""Motto_DE"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""TechTags"" text;
                        ALTER TABLE ""Profiles"" ADD COLUMN IF NOT EXISTS ""IsOpenToOffers"" boolean DEFAULT true;

                        CREATE TABLE IF NOT EXISTS ""Skills"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            ""Name"" text NOT NULL,
                            ""Percentage"" integer NOT NULL,
                            CONSTRAINT ""PK_Skills"" PRIMARY KEY (""Id"")
                        );

                        INSERT INTO ""__EFMigrationsHistory"" (""MigrationId"", ""ProductVersion"")
                        VALUES ('20260714132915_InitialCreate', '8.0.8')
                        ON CONFLICT (""MigrationId"") DO NOTHING;
                    ");
                }
                catch (System.Exception ex)
                {
                    System.Console.WriteLine($"[Schema Check Warning] {ex.Message}");
                }
            }

            _db.Database.Migrate();

            SeedUsers();
            SeedProfileDetails();
            SeedSkills();

            _db.SaveChanges();
        }

        private void SeedUsers()
        {
            if (!_db.Users.Any())
            {
                _db.Users.Add(new UserEntity
                {
                    Id = 1,
                    Username = "admin",
                    PasswordHash = PasswordHasher.HashPassword("admin123")
                });
            }
        }

        private void SeedProfileDetails()
        {
            var profile = _db.Profiles.FirstOrDefault();
            if (profile != null)
            {
                bool modified = false;
                if (string.IsNullOrEmpty(profile.Job_TR))
                {
                    profile.Job_TR = "Yazılım Mühendisi @ Apex Tech";
                    profile.Job_EN = "Software Engineer @ Apex Tech";
                    profile.Job_DE = "Softwareentwickler @ Apex Tech";
                    modified = true;
                }
                if (string.IsNullOrEmpty(profile.Education_TR))
                {
                    profile.Education_TR = "Erciyes Üni. Yazılım Müh. (3. Sınıf)";
                    profile.Education_EN = "Erciyes Uni. Software Eng. (3rd Grade)";
                    profile.Education_DE = "Erciyes Uni. Softwaretechnik (3. Klasse)";
                    modified = true;
                }
                if (string.IsNullOrEmpty(profile.Motto_TR))
                {
                    profile.Motto_TR = "\"Fikirleri koda, kodları yaşayan ve ölçeklenebilir ürünlere dönüştürüyorum.\"";
                    profile.Motto_EN = "\"I transform ideas into code, and code into living, scalable products.\"";
                    profile.Motto_DE = "\"Ich verwandele Ideen in Code und Code in lebendige, skalierbare Produkte.\"";
                    modified = true;
                }
                if (string.IsNullOrEmpty(profile.TechTags))
                {
                    profile.TechTags = ".NET Core, EF Core, Angular, Agentic AI, Fedora Linux";
                    modified = true;
                }
                if (!profile.IsOpenToOffers && _db.Entry(profile).State == EntityState.Detached)
                {
                    profile.IsOpenToOffers = true;
                    modified = true;
                }

                if (modified)
                {
                    _db.Profiles.Update(profile);
                }
            }
        }

        private void SeedSkills()
        {
            if (!_db.Skills.Any())
            {
                _db.Skills.AddRange(new List<SkillEntity>
                {
                    new SkillEntity { Name = "JavaScript & TypeScript", Percentage = 92 },
                    new SkillEntity { Name = "C# & .NET Core", Percentage = 88 },
                    new SkillEntity { Name = "HTML5 & Vanilla CSS3", Percentage = 95 },
                    new SkillEntity { Name = "React & Next.js", Percentage = 90 },
                    new SkillEntity { Name = "Node.js / Express", Percentage = 85 },
                    new SkillEntity { Name = "SQL & NoSQL Database Systems", Percentage = 80 }
                });
            }
        }
    }
}
