// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702191423_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Server.Models.ArticleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailText_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailText_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailText_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTag_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTag_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTag_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Server.Models.ProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Github")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Linkedin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pubs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Repos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Twitter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Server.Models.ProjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailText_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailText_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailText_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTag_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTag_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTag_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tech")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
