// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715192406_AddSkillsAndProfileDetails")]
    partial class AddSkillsAndProfileDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.ArticleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailText_DE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailText_EN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailText_TR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Excerpt_DE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Excerpt_EN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Excerpt_TR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReadTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubTag_DE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubTag_EN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubTag_TR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title_DE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title_EN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title_TR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Server.Models.MessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Server.Models.ProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio_DE")
                        .HasColumnType("text");

                    b.Property<string>("Bio_EN")
                        .HasColumnType("text");

                    b.Property<string>("Bio_TR")
                        .HasColumnType("text");

                    b.Property<string>("CvPdfUrl_DE")
                        .HasColumnType("text");

                    b.Property<string>("CvPdfUrl_EN")
                        .HasColumnType("text");

                    b.Property<string>("CvPdfUrl_TR")
                        .HasColumnType("text");

                    b.Property<string>("CvText_DE")
                        .HasColumnType("text");

                    b.Property<string>("CvText_EN")
                        .HasColumnType("text");

                    b.Property<string>("CvText_TR")
                        .HasColumnType("text");

                    b.Property<string>("Education_DE")
                        .HasColumnType("text");

                    b.Property<string>("Education_EN")
                        .HasColumnType("text");

                    b.Property<string>("Education_TR")
                        .HasColumnType("text");

                    b.Property<string>("Github")
                        .HasColumnType("text");

                    b.Property<string>("Instagram")
                        .HasColumnType("text");

                    b.Property<bool>("IsOpenToOffers")
                        .HasColumnType("boolean");

                    b.Property<string>("Job_DE")
                        .HasColumnType("text");

                    b.Property<string>("Job_EN")
                        .HasColumnType("text");

                    b.Property<string>("Job_TR")
                        .HasColumnType("text");

                    b.Property<string>("Linkedin")
                        .HasColumnType("text");

                    b.Property<string>("Medium")
                        .HasColumnType("text");

                    b.Property<string>("Motto_DE")
                        .HasColumnType("text");

                    b.Property<string>("Motto_EN")
                        .HasColumnType("text");

                    b.Property<string>("Motto_TR")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Pubs")
                        .HasColumnType("integer");

                    b.Property<int>("Repos")
                        .HasColumnType("integer");

                    b.Property<string>("Tag_DE")
                        .HasColumnType("text");

                    b.Property<string>("Tag_EN")
                        .HasColumnType("text");

                    b.Property<string>("Tag_TR")
                        .HasColumnType("text");

                    b.Property<string>("TechTags")
                        .HasColumnType("text");

                    b.Property<string>("Title_DE")
                        .HasColumnType("text");

                    b.Property<string>("Title_EN")
                        .HasColumnType("text");

                    b.Property<string>("Title_TR")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Server.Models.ProjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DemoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description_DE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description_EN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description_TR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailText_DE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailText_EN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailText_TR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubTag_DE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubTag_EN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubTag_TR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tech")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title_DE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title_EN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title_TR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Server.Models.SkillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Percentage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Server.Models.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
