// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Server.Models.ArticleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailText_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailText_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailText_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTag_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTag_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTag_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Server.Models.MessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Server.Models.ProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio_DE")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio_EN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio_TR")
                        .HasColumnType("TEXT");

                    b.Property<string>("Github")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instagram")
                        .HasColumnType("TEXT");

                    b.Property<string>("Linkedin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medium")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pubs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Repos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag_DE")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag_EN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag_TR")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_DE")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_EN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_TR")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Server.Models.ProjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailText_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailText_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailText_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTag_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTag_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTag_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tech")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_DE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_EN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title_TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Server.Models.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
